#!/bin/bash

source .env

ACCESS_TOKEN=$(curl -X POST -s "$API_URL/token/new/" \
  -H "accept: application/json" \
  -H  "Content-Type: application/json" \
  -d "{\"secret_id\":\"$SECRET_ID\", \"secret_key\":\"$SECRET_KEY\"}" \
| sed -r "s/(.*)access\":\"//g;s/\",\"access_expires(.*)//g")
