#!/bin/bash

DATE_FROM="$1"
DATE_TO="$2"

TRANSACTION_IDS=$(./get_transaction_ids "$DATE_FROM" "$DATE_TO")

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

OLDIFS="$IFS"
IFS=$'\n'
DEBER=0.0
HABER=0.0
for TRANSACTION_ID in $TRANSACTION_IDS; do
	AMOUNT=$(./get_transaction_amount "$TRANSACTION_ID" | tr "," ".")
	CREDITOR_NAME=$(./get_transaction_creditorName "$TRANSACTION_ID")
	REMITTANCE=$(./get_transaction_remittance "$TRANSACTION_ID")
	if [[ "$CREDITOR_NAME" != "null" ]]; then
		printf "Info: ${RED}$CREDITOR_NAME${NC}\n"
	fi
	if [[ "$REMITTANCE" != "null" ]]; then
		printf "Info: ${RED}$REMITTANCE${NC}\n"
	fi

	printf "Cantidad: ${RED}$AMOUNT €${NC}\n"
	read -p "Añadir transacción? Yes/No [Y] " YesNo
	if [[ "$YesNo" != *[Nn]* ]]; then
		if [[ $AMOUNT != "-"* ]]; then
			HABER=$(echo $HABER + $AMOUNT | bc)
		else
			DEBER=$(echo $DEBER + $AMOUNT | bc)
		fi
		printf "${GREEN}Transacción añadida${NC}\n"
	else
		printf "${RED}Transacción ignorada${NC}\n"
	fi

	echo ""
	echo "------------------"
	echo "------------------"
	echo ""
done
printf "HABER: ${GREEN}$HABER €${NC}\n"
printf "DEBER: ${RED}$DEBER €${NC}\n"
IFS=$OLDIFS

rm -rf transactions.json transactions_filtered.json
