#!/bin/bash

source ./auth

agreement=$(curl -X POST -s "$API_URL/agreements/enduser/" \
  -H  "accept: application/json" \
  -H  "Content-Type: application/json" \
  -H  "Authorization: Bearer $ACCESS_TOKEN" \
  -d "{\"institution_id\": \"$INSTITUTION_ID\", \"access_scope\": [\"balances\", \"details\", \"transactions\"]}")

data=$(curl -X POST -s "$API_URL/requisitions/" \
  -H "accept: application/json" \
  -H  "Authorization: Bearer $ACCESS_TOKEN" \
  -H  "Content-Type: application/json" \
  -d "{\"redirect\": \"http://127.0.0.1:6655\", \"institution_id\": \"$INSTITUTION_ID\"}")

link=$(echo $data | jq -r ".link")

REQUISITION_ID=$(echo $data | jq -r ".id")

xdg-open $link 2>/dev/null

./websocket $REQUISITION_ID

result=$?

if [ $result -eq 0 ]; then
  data=$(curl -X GET -s "$API_URL/requisitions/$REQUISITION_ID/" \
  -H  "accept: application/json" \
  -H  "Authorization: Bearer $ACCESS_TOKEN")

  sed -i '/^ACCOUNT_ID/d' .env

  ACCOUNT_ID=$(echo $data | jq -r ".accounts[0]")

  echo "ACCOUNT_ID=$ACCOUNT_ID" >> .env

  echo "Account Id updated!"
  exit
fi

echo "Error with process. Please try again"


